// <auto-generated />
using System;
using System.Collections.Generic;
using MarqSpec.TradingCopilot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MarqSpec.TradingCopilot.Data.Migrations
{
    [DbContext(typeof(TradingCopilotDbContext))]
    [Migration("20260815050936_AddChatConversations")]
    partial class AddChatConversations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<bool>("CanTrade")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int?>("StageOverride")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VenueAccountKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "VenueAccountKey")
                        .IsUnique();

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_StageOverride_NotUnknown", "\"StageOverride\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.AiUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("Feature")
                        .HasColumnType("integer");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int?>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("AiUsage", null, t =>
                        {
                            t.HasCheckConstraint("CK_AiUsage_EstimatedCostUsd_NotNegative", "\"EstimatedCostUsd\" >= 0");

                            t.HasCheckConstraint("CK_AiUsage_Feature_NotUnknown", "\"Feature\" <> 0");

                            t.HasCheckConstraint("CK_AiUsage_InputTokens_NotNegative", "\"InputTokens\" >= 0");

                            t.HasCheckConstraint("CK_AiUsage_LatencyMs_NotNegative", "\"LatencyMs\" >= 0");

                            t.HasCheckConstraint("CK_AiUsage_Outcome_NotUnknown", "\"Outcome\" <> 0");

                            t.HasCheckConstraint("CK_AiUsage_OutputTokens_NotNegative", "\"OutputTokens\" >= 0");

                            t.HasCheckConstraint("CK_AiUsage_Tier_NotUnknownOrNull", "\"Tier\" IS NULL OR \"Tier\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("After")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Before")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Placement")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StopPlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SyntheticRisk")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("AuditRecords", t =>
                        {
                            t.HasCheckConstraint("CK_AuditRecords_Action_NotUnknown", "\"Action\" <> 0");

                            t.HasCheckConstraint("CK_AuditRecords_Placement_NotUnknown", "\"Placement\" <> 0");

                            t.HasCheckConstraint("CK_AuditRecords_Source_MatchesAction", "(\"Action\" IN (5, 6, 7)) = (\"Source\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_AuditRecords_Source_NotUnknown", "\"Source\" IS NULL OR \"Source\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.BarRecord", b =>
                {
                    b.Property<string>("Venue")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Instrument")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Venue", "Instrument", "ResolutionMinutes", "BucketStart");

                    b.HasIndex("Instrument", "ResolutionMinutes", "BucketStart");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_ChatMessages_ConversationId_Sequence");

                    b.ToTable("ChatMessages", t =>
                        {
                            t.HasCheckConstraint("CK_ChatMessages_Role_NotUnknown", "\"Role\" <> 0");

                            t.HasCheckConstraint("CK_ChatMessages_Sequence_Positive", "\"Sequence\" > 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.ConditionalOrderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CancelDriftPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FiredOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<decimal>("PointValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SafetyStopPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("numeric");

                    b.Property<int>("TriggerDirection")
                        .HasColumnType("integer");

                    b.Property<decimal>("TriggerPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WorkingStopPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("FiredOrderId");

                    b.HasIndex("Status");

                    b.HasIndex("SuggestionId");

                    b.ToTable("ConditionalOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConditionalOrders_CancelDrift_StaleSide", "\"CancelDriftPrice\" IS NULL OR (\"TriggerDirection\" = 1 AND \"CancelDriftPrice\" < \"TriggerPrice\") OR (\"TriggerDirection\" = 2 AND \"CancelDriftPrice\" > \"TriggerPrice\")");

                            t.HasCheckConstraint("CK_ConditionalOrders_Direction_NotUnknown", "\"TriggerDirection\" <> 0");

                            t.HasCheckConstraint("CK_ConditionalOrders_Mode_NotUndeclared", "\"Mode\" <> 0");

                            t.HasCheckConstraint("CK_ConditionalOrders_Size_Positive", "\"Size\" > 0");

                            t.HasCheckConstraint("CK_ConditionalOrders_Status_NotUnknown", "\"Status\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("UserId", "FirmId", "Platform")
                        .IsUnique();

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.EmbeddingRecord", b =>
                {
                    b.Property<int>("OwnerKind")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OwnerKind", "OwnerId", "Model");

                    b.HasIndex("OwnerKind", "RecordedAt");

                    b.ToTable("Embeddings");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Event", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Sequence");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.EventCursor", b =>
                {
                    b.Property<string>("ConsumerGroup")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint");

                    b.HasKey("ConsumerGroup");

                    b.ToTable("EventCursors");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Fill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VenueFillKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "VenueFillKey")
                        .IsUnique();

                    b.ToTable("Fills", t =>
                        {
                            t.HasCheckConstraint("CK_Fills_Size_Positive", "\"Size\" > 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Firm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Firms");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.FirmStageConvention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CapitalAtRisk")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "Stage")
                        .IsUnique();

                    b.ToTable("FirmStageConventions", t =>
                        {
                            t.HasCheckConstraint("CK_FirmStageConvention_Stage_NotUnknown", "\"Stage\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.GateDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Advisories")
                        .HasColumnType("jsonb");

                    b.Property<int>("ApprovedQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("BindingLayer")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("AccountId", "DecidedAt");

                    b.ToTable("GateDecisions", (string)null);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.IndicatorValueRecord", b =>
                {
                    b.Property<string>("Venue")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Instrument")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Indicator")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Venue", "Instrument", "ResolutionMinutes", "Indicator", "Period", "BucketStart");

                    b.HasIndex("Instrument", "ResolutionMinutes", "Indicator", "Period", "BucketStart");

                    b.ToTable("IndicatorValues");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.KillSwitchState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Engaged")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EngagedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("KillSwitchStates");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.NewsRecord", b =>
                {
                    b.Property<string>("DedupKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.PrimitiveCollection<List<string>>("MatchedInstruments")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("MatchedTopics")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RelevanceResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("RelevanceVersion")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<string>>("SourceFeeds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tickers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("DedupKey");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("RelevanceVersion");

                    b.ToTable("News");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.NewsTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Instrument")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<List<string>>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NewsTopics", t =>
                        {
                            t.HasCheckConstraint("CK_NewsTopics_Scope_NotUnknown", "\"Scope\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.NotificationOutboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasFilter("\"DeliveredAt\" IS NULL");

                    b.HasIndex("DeliveredAt", "CreatedAt");

                    b.ToTable("NotificationOutbox", t =>
                        {
                            t.HasCheckConstraint("CK_NotificationOutbox_Severity_NotUnknown", "\"Severity\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EntryMethod")
                        .HasColumnType("integer");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("LimitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PointValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SafetyStopPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VenueOrderKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("WorkingStopPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId");

                    b.HasIndex("AccountId", "VenueOrderKey")
                        .IsUnique();

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_EntryMethod_NotUnknown", "\"EntryMethod\" IS NULL OR \"EntryMethod\" <> 0");

                            t.HasCheckConstraint("CK_Orders_Mode_NotUndeclared", "\"Mode\" <> 0");

                            t.HasCheckConstraint("CK_Orders_Size_Positive", "\"Size\" > 0");

                            t.HasCheckConstraint("CK_Orders_Status_NotUnknown", "\"Status\" <> 0");

                            t.HasCheckConstraint("CK_Orders_TakeProfit_WinningSide", "\"TakeProfitPrice\" IS NULL OR (\"Side\" = 0 AND \"TakeProfitPrice\" > \"EntryPrice\") OR (\"Side\" = 1 AND \"TakeProfitPrice\" < \"EntryPrice\")");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.PriceLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Bottom")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("FormedAtBucket")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<decimal>("Significance")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("TimeframeMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Top")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("TouchCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Venue", "Instrument", "TimeframeMinutes", "Active");

                    b.ToTable("PriceLevels", t =>
                        {
                            t.HasCheckConstraint("CK_PriceLevels_Bottom_Positive", "\"Bottom\" > 0");

                            t.HasCheckConstraint("CK_PriceLevels_Kind_NotUnknown", "\"Kind\" <> 0");

                            t.HasCheckConstraint("CK_PriceLevels_Timeframe_Positive", "\"TimeframeMinutes\" > 0");

                            t.HasCheckConstraint("CK_PriceLevels_ZoneOrdered", "\"Top\" > \"Bottom\"");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.RelevanceConfigState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RelevanceConfigStates");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.RiskProfileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AccountProfitTarget")
                        .HasColumnType("numeric");

                    b.Property<int>("ConsistencyEnforcement")
                        .HasColumnType("integer");

                    b.Property<decimal>("DailyDrawdownGovernor")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DailyLossLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DailyProfitTarget")
                        .HasColumnType("numeric");

                    b.Property<int>("DefaultEntryAction")
                        .HasColumnType("integer");

                    b.Property<int>("FloorSource")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LocksAt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxBestDayFraction")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxContractsPerOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxDrawdownPerTrade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PerTradeRiskFraction")
                        .HasColumnType("numeric");

                    b.Property<int>("SizingBasis")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartingBalance")
                        .HasColumnType("numeric");

                    b.Property<bool>("StopForDayAtProfitTarget")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TargetRewardRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TrailingAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TrailingMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("RiskProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_RiskProfiles_DailyDrawdownGovernor_Positive", "\"DailyDrawdownGovernor\" > 0");

                            t.HasCheckConstraint("CK_RiskProfiles_MaxBestDayFraction_ZeroToOne", "\"MaxBestDayFraction\" > 0 AND \"MaxBestDayFraction\" <= 1");

                            t.HasCheckConstraint("CK_RiskProfiles_MaxContractsPerOrder_NotNegative", "\"MaxContractsPerOrder\" >= 0");

                            t.HasCheckConstraint("CK_RiskProfiles_MaxDrawdownPerTrade_Positive", "\"MaxDrawdownPerTrade\" > 0");

                            t.HasCheckConstraint("CK_RiskProfiles_PerTradeRiskFraction_ZeroToOne", "\"PerTradeRiskFraction\" > 0 AND \"PerTradeRiskFraction\" <= 1");

                            t.HasCheckConstraint("CK_RiskProfiles_StartingBalance_Positive", "\"StartingBalance\" > 0");

                            t.HasCheckConstraint("CK_RiskProfiles_TargetRewardRatio_Positive", "\"TargetRewardRatio\" > 0");

                            t.HasCheckConstraint("CK_RiskProfiles_TrailingAmount_Positive", "\"TrailingAmount\" > 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.SoftSignalFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("NewsDedupKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "NewsDedupKey")
                        .IsUnique();

                    b.ToTable("SoftSignalFeedbacks", t =>
                        {
                            t.HasCheckConstraint("CK_SoftSignalFeedback_Kind_NotUnknown", "\"Kind\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.StopPlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualStopPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProximityMetric")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProximityValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SafetyStopPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Staging")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("StopPlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_StopPlans_ProximityMetric_NotUnknown", "\"ProximityMetric\" <> 0");

                            t.HasCheckConstraint("CK_StopPlans_ProximityValue_Positive", "\"ProximityValue\" > 0");

                            t.HasCheckConstraint("CK_StopPlans_SafetyBeyondActual", "(\"Side\" = 0 AND \"SafetyStopPrice\" < \"ActualStopPrice\" AND \"ActualStopPrice\" < \"EntryPrice\") OR (\"Side\" = 1 AND \"SafetyStopPrice\" > \"ActualStopPrice\" AND \"ActualStopPrice\" > \"EntryPrice\")");

                            t.HasCheckConstraint("CK_StopPlans_Staging_NotUnknown", "\"Staging\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CitedIndicator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("CitedPeriod")
                        .HasColumnType("integer");

                    b.Property<int>("CitedResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StateChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StopPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("TriggerFiringId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SupersedesId");

                    b.HasIndex("UserId", "State", "CreatedAt")
                        .HasDatabaseName("IX_Suggestions_UserId_State_CreatedAt");

                    b.ToTable("Suggestions", t =>
                        {
                            t.HasCheckConstraint("CK_Suggestions_Confidence_Range", "\"Confidence\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Suggestions_ExpiresAfterCreated", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_Suggestions_Mode_NotUndeclared", "\"Mode\" <> 0");

                            t.HasCheckConstraint("CK_Suggestions_Size_Positive", "\"Size\" > 0");

                            t.HasCheckConstraint("CK_Suggestions_State_NotUnknown", "\"State\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.SuggestionDisposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deviations")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Reasons")
                        .HasColumnType("integer");

                    b.Property<Guid>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TakenEntryPrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("TakenSize")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TakenStopPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TakenTargetPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId")
                        .IsUnique()
                        .HasDatabaseName("IX_SuggestionDispositions_SuggestionId");

                    b.ToTable("SuggestionDispositions", t =>
                        {
                            t.HasCheckConstraint("CK_SuggestionDispositions_Deviations_MatchModified", "(\"Kind\" = 2) = (\"Deviations\" <> 0)");

                            t.HasCheckConstraint("CK_SuggestionDispositions_Kind_NotUnknown", "\"Kind\" <> 0");

                            t.HasCheckConstraint("CK_SuggestionDispositions_TakeSnapshot", "(\"Kind\" IN (1, 2) AND \"TakenEntryPrice\" IS NOT NULL AND \"TakenStopPrice\" IS NOT NULL AND \"TakenSize\" IS NOT NULL) OR (\"Kind\" = 3 AND \"TakenEntryPrice\" IS NULL AND \"TakenStopPrice\" IS NULL AND \"TakenTargetPrice\" IS NULL AND \"TakenSize\" IS NULL)");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.TickerInstrumentMap", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Instrument")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Ticker", "Instrument");

                    b.ToTable("TickerInstrumentMaps");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosingFillId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OpeningFillId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RealizedPnL")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpeningFillId");

                    b.HasIndex("SuggestionId");

                    b.HasIndex("AccountId", "ClosedAt");

                    b.HasIndex("ClosingFillId", "OpeningFillId")
                        .IsUnique()
                        .HasFilter("\"ClosingFillId\" IS NOT NULL AND \"OpeningFillId\" IS NOT NULL");

                    b.ToTable("Trades", t =>
                        {
                            t.HasCheckConstraint("CK_Trades_Mode_NotUndeclared", "\"Mode\" <> 0");

                            t.HasCheckConstraint("CK_Trades_Size_Positive", "\"Size\" > 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.TriggerFiringRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Comparison")
                        .HasColumnType("integer");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("FiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ObservedValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<Guid>("TriggerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TriggerId");

                    b.ToTable("TriggerFirings", (string)null);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.TriggerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("ArmCycle")
                        .HasColumnType("integer");

                    b.Property<int>("ArmState")
                        .HasColumnType("integer");

                    b.Property<int>("Comparison")
                        .HasColumnType("integer");

                    b.Property<int>("ConditionKind")
                        .HasColumnType("integer");

                    b.Property<int>("Confirmation")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Hysteresis")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("LastEvaluatedValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset?>("LastFiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Route")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StalenessReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset?>("UnmeasurableSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Confirmation", "Enabled", "Route");

                    b.ToTable("Triggers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Triggers_AgentReview_RequiresAccountAndSize", "\"Route\" <> 2 OR (\"AccountId\" IS NOT NULL AND \"Size\" > 0)");

                            t.HasCheckConstraint("CK_Triggers_Comparison_NotUnknown", "\"Comparison\" <> 0");

                            t.HasCheckConstraint("CK_Triggers_ConditionKind_NotUnknown", "\"ConditionKind\" <> 0");

                            t.HasCheckConstraint("CK_Triggers_Confirmation_Known", "\"Confirmation\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Triggers_Hysteresis_PositiveOrNull", "\"Hysteresis\" IS NULL OR \"Hysteresis\" > 0");

                            t.HasCheckConstraint("CK_Triggers_Mechanical_NoAccount", "\"Route\" = 2 OR (\"AccountId\" IS NULL AND \"Size\" IS NULL)");

                            t.HasCheckConstraint("CK_Triggers_Period_Positive", "\"Period\" > 0");

                            t.HasCheckConstraint("CK_Triggers_ResolutionMinutes_Positive", "\"ResolutionMinutes\" > 0");

                            t.HasCheckConstraint("CK_Triggers_Route_NotUnknown", "\"Route\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsPrimaryOperator")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Account", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Connection", null)
                        .WithMany("Accounts")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.ConditionalOrderRecord", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("FiredOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Connection", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Firm", null)
                        .WithMany()
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Fill", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.FirmStageConvention", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Firm", null)
                        .WithMany("StageConventions")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.GateDecisionRecord", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Order", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.RiskProfileRecord", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("MarqSpec.TradingCopilot.Data.Entities.RiskProfileRecord", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.StopPlanRecord", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Order", null)
                        .WithOne()
                        .HasForeignKey("MarqSpec.TradingCopilot.Data.Entities.StopPlanRecord", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Suggestion", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.SuggestionDisposition", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Trade", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Fill", null)
                        .WithMany()
                        .HasForeignKey("ClosingFillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Fill", null)
                        .WithMany()
                        .HasForeignKey("OpeningFillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.TriggerRecord", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Connection", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Firm", b =>
                {
                    b.Navigation("StageConventions");
                });
#pragma warning restore 612, 618
        }
    }
}
