// <auto-generated />
using System;
using MarqSpec.TradingCopilot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarqSpec.TradingCopilot.Data.Migrations
{
    [DbContext(typeof(TradingCopilotDbContext))]
    [Migration("20260726183407_AddConnectionLifecycle")]
    partial class AddConnectionLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<bool>("CanTrade")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int?>("StageOverride")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VenueAccountKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "VenueAccountKey")
                        .IsUnique();

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_StageOverride_NotUnknown", "\"StageOverride\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("After")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Before")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Placement")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StopPlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SyntheticRisk")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("AuditRecords", t =>
                        {
                            t.HasCheckConstraint("CK_AuditRecords_Action_NotUnknown", "\"Action\" <> 0");

                            t.HasCheckConstraint("CK_AuditRecords_Placement_NotUnknown", "\"Placement\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.ConditionalOrderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CancelDriftPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FiredOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<decimal>("PointValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SafetyStopPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("numeric");

                    b.Property<int>("TriggerDirection")
                        .HasColumnType("integer");

                    b.Property<decimal>("TriggerPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WorkingStopPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("FiredOrderId");

                    b.HasIndex("Status");

                    b.HasIndex("SuggestionId");

                    b.ToTable("ConditionalOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConditionalOrders_CancelDrift_StaleSide", "\"CancelDriftPrice\" IS NULL OR (\"TriggerDirection\" = 1 AND \"CancelDriftPrice\" < \"TriggerPrice\") OR (\"TriggerDirection\" = 2 AND \"CancelDriftPrice\" > \"TriggerPrice\")");

                            t.HasCheckConstraint("CK_ConditionalOrders_Direction_NotUnknown", "\"TriggerDirection\" <> 0");

                            t.HasCheckConstraint("CK_ConditionalOrders_Mode_NotUndeclared", "\"Mode\" <> 0");

                            t.HasCheckConstraint("CK_ConditionalOrders_Size_Positive", "\"Size\" > 0");

                            t.HasCheckConstraint("CK_ConditionalOrders_Status_NotUnknown", "\"Status\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("UserId", "FirmId", "Platform")
                        .IsUnique();

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Event", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Sequence");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.EventCursor", b =>
                {
                    b.Property<string>("ConsumerGroup")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint");

                    b.HasKey("ConsumerGroup");

                    b.ToTable("EventCursors");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Fill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VenueFillKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "VenueFillKey")
                        .IsUnique();

                    b.ToTable("Fills", t =>
                        {
                            t.HasCheckConstraint("CK_Fills_Size_Positive", "\"Size\" > 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Firm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Firms");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.FirmStageConvention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CapitalAtRisk")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "Stage")
                        .IsUnique();

                    b.ToTable("FirmStageConventions", t =>
                        {
                            t.HasCheckConstraint("CK_FirmStageConvention_Stage_NotUnknown", "\"Stage\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.GateDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovedQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("BindingLayer")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("AccountId", "DecidedAt");

                    b.ToTable("GateDecisions", (string)null);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.KillSwitchState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Engaged")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EngagedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("KillSwitchStates");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EntryMethod")
                        .HasColumnType("integer");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("LimitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PointValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SafetyStopPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VenueOrderKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("WorkingStopPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId");

                    b.HasIndex("AccountId", "VenueOrderKey")
                        .IsUnique();

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_EntryMethod_NotUnknown", "\"EntryMethod\" IS NULL OR \"EntryMethod\" <> 0");

                            t.HasCheckConstraint("CK_Orders_Mode_NotUndeclared", "\"Mode\" <> 0");

                            t.HasCheckConstraint("CK_Orders_Size_Positive", "\"Size\" > 0");

                            t.HasCheckConstraint("CK_Orders_Status_NotUnknown", "\"Status\" <> 0");

                            t.HasCheckConstraint("CK_Orders_TakeProfit_WinningSide", "\"TakeProfitPrice\" IS NULL OR (\"Side\" = 0 AND \"TakeProfitPrice\" > \"EntryPrice\") OR (\"Side\" = 1 AND \"TakeProfitPrice\" < \"EntryPrice\")");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.RiskProfileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AccountProfitTarget")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyDrawdownGovernor")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DailyLossLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DailyProfitTarget")
                        .HasColumnType("numeric");

                    b.Property<int>("DefaultEntryAction")
                        .HasColumnType("integer");

                    b.Property<int>("FloorSource")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LocksAt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxBestDayFraction")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxContractsPerOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxDrawdownPerTrade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PerTradeRiskFraction")
                        .HasColumnType("numeric");

                    b.Property<int>("SizingBasis")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartingBalance")
                        .HasColumnType("numeric");

                    b.Property<bool>("StopForDayAtProfitTarget")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TargetRewardRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TrailingAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TrailingMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("RiskProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_RiskProfiles_DailyDrawdownGovernor_Positive", "\"DailyDrawdownGovernor\" > 0");

                            t.HasCheckConstraint("CK_RiskProfiles_MaxBestDayFraction_ZeroToOne", "\"MaxBestDayFraction\" > 0 AND \"MaxBestDayFraction\" <= 1");

                            t.HasCheckConstraint("CK_RiskProfiles_MaxContractsPerOrder_NotNegative", "\"MaxContractsPerOrder\" >= 0");

                            t.HasCheckConstraint("CK_RiskProfiles_MaxDrawdownPerTrade_Positive", "\"MaxDrawdownPerTrade\" > 0");

                            t.HasCheckConstraint("CK_RiskProfiles_PerTradeRiskFraction_ZeroToOne", "\"PerTradeRiskFraction\" > 0 AND \"PerTradeRiskFraction\" <= 1");

                            t.HasCheckConstraint("CK_RiskProfiles_StartingBalance_Positive", "\"StartingBalance\" > 0");

                            t.HasCheckConstraint("CK_RiskProfiles_TargetRewardRatio_Positive", "\"TargetRewardRatio\" > 0");

                            t.HasCheckConstraint("CK_RiskProfiles_TrailingAmount_Positive", "\"TrailingAmount\" > 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.StopPlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualStopPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProximityMetric")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProximityValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SafetyStopPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Staging")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("StopPlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_StopPlans_ProximityMetric_NotUnknown", "\"ProximityMetric\" <> 0");

                            t.HasCheckConstraint("CK_StopPlans_ProximityValue_Positive", "\"ProximityValue\" > 0");

                            t.HasCheckConstraint("CK_StopPlans_SafetyBeyondActual", "(\"Side\" = 0 AND \"SafetyStopPrice\" < \"ActualStopPrice\" AND \"ActualStopPrice\" < \"EntryPrice\") OR (\"Side\" = 1 AND \"SafetyStopPrice\" > \"ActualStopPrice\" AND \"ActualStopPrice\" > \"EntryPrice\")");

                            t.HasCheckConstraint("CK_StopPlans_Staging_NotUnknown", "\"Staging\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<decimal>("StopPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Suggestions", t =>
                        {
                            t.HasCheckConstraint("CK_Suggestions_Mode_NotUndeclared", "\"Mode\" <> 0");

                            t.HasCheckConstraint("CK_Suggestions_Size_Positive", "\"Size\" > 0");

                            t.HasCheckConstraint("CK_Suggestions_State_NotUnknown", "\"State\" <> 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RealizedPnL")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SuggestionId");

                    b.ToTable("Trades", t =>
                        {
                            t.HasCheckConstraint("CK_Trades_Mode_NotUndeclared", "\"Mode\" <> 0");

                            t.HasCheckConstraint("CK_Trades_Size_Positive", "\"Size\" > 0");
                        });
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsPrimaryOperator")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Account", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Connection", null)
                        .WithMany("Accounts")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.ConditionalOrderRecord", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("FiredOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Connection", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Firm", null)
                        .WithMany()
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Fill", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.FirmStageConvention", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Firm", null)
                        .WithMany("StageConventions")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.GateDecisionRecord", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Order", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.RiskProfileRecord", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("MarqSpec.TradingCopilot.Data.Entities.RiskProfileRecord", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.StopPlanRecord", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Order", null)
                        .WithOne()
                        .HasForeignKey("MarqSpec.TradingCopilot.Data.Entities.StopPlanRecord", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Suggestion", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Trade", b =>
                {
                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarqSpec.TradingCopilot.Data.Entities.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Connection", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MarqSpec.TradingCopilot.Data.Entities.Firm", b =>
                {
                    b.Navigation("StageConventions");
                });
#pragma warning restore 612, 618
        }
    }
}
