/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email + password; returns a JWT bearer token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The currently authenticated user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue an invitation to create an account (primary operator only). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IssueInvitationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem an invitation token to create an account; returns a JWT. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptInviteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the operator's registered firms. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Register a firm the operator trades with. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFirmRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firms/{id}/conventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Declare what each account stage means at a firm. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeclareConventionsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the operator's connections. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a firm connection (login). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConnectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the accounts discovered through a connection. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{id}/accounts/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover accounts through a connection (mode from the firm's declared conventions). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rotates which credential key a connection names (gh#210, R-17, ADR-0015). */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The connection. */
                    id: string;
                };
                cookie?: never;
            };
            /** @description The caller's cancellation token. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RotateCredentialsRequest"];
                };
            };
            responses: {
                /** @description The updated connection, or a refusal. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deactivates a connection and cascades to its accounts — a soft delete (gh#210, R-17, R-20). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The connection. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok on deactivation (idempotent), or 404 when it is not the operator's. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set a manual stage override on an account. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetStageOverrideRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Clear the manual stage override on an account. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The account's declared risk profile, if any. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Declare the account's risk rules (validated whole; refused on any violation). */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeclareRiskProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/risk/headroom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today's remaining daily-loss budget and target progress, readable without a send (gh#587). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the operator's triggers. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Author a standing deterministic trigger. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTriggerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triggers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a trigger by id. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a trigger. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a trigger. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PatchTriggerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/triggers/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a trigger that requires operator confirmation. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relevance/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the ticker↔instrument maps. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a ticker↔instrument relevance map. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TickerMapRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relevance/maps/{ticker}/{instrument}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a ticker↔instrument map. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticker: string;
                    instrument: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relevance/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List relevance topics. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a relevance topic. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TopicRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relevance/topics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a relevance topic by id. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a relevance topic. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a relevance topic. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TopicRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The personalized feed: recent news re-ranked by the operator's decayed salience profile. */
        get: {
            parameters: {
                query?: {
                    limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stars or mutes a news item — an upsert: re-rating replaces, so an item carries at most one feedback. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewsFeedbackRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Un-stars / un-mutes an item — the personalization round-trips, so its salience returns to base. */
        delete: {
            parameters: {
                query: {
                    dedupKey: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists an account's suggestions, newest first. Defaults to the <b>actionable</b> set
         *     (SuggestionState.Active) — a decision surface should not open on rows that can no longer be
         *     acted on; the rest stay reachable by explicit filter and by id.
         */
        get: {
            parameters: {
                query?: {
                    /** @description The lifecycle state to filter to; omitted means active only. */
                    state?: components["schemas"]["SuggestionState"];
                    /** @description The page size; clamped to the configured maximum. */
                    limit?: number | string;
                };
                header?: never;
                path: {
                    /** @description The account whose suggestions to list. */
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The page of suggestions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reads one suggestion by id, in <b>any</b> state — an expired or superseded row stays readable, because the
         *     journal outlives the decision window.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The suggestion's id. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The suggestion, or 404 when it does not exist or belongs to another operator. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{id}/pass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Records a <b>neutral pass</b> on a suggestion (gh#547, R-4/R-8): `POST /suggestions/{id}/pass`. A pass
         *     touches no order, gate or venue — it writes one SuggestionDisposition so the R-9 learning loop
         *     has the operator's decline to read.
         * @description A pass on an <b>already stale or expired</b> suggestion is still accepted — the operator's note is worth
         *     keeping, and lifecycle state is the clock's, not the disposition's (gh#539). One disposition per suggestion:
         *     a second <b>conflicts</b> (409) rather than overwriting, because the journal records the decision, not the
         *     latest edit.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The suggestion to pass on. */
                    id: string;
                };
                cookie?: never;
            };
            /** @description The caller's cancellation token. */
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["SuggestionPassRequest"];
                };
            };
            responses: {
                /** @description The recorded disposition, 404 when the suggestion is not the caller's, or 409 when already disposed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions/{id}/take": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arm an editable, unsent order ticket from a suggestion. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["SuggestionTakeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the account's resting working orders from venue truth. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Send an order through the full risk gate (direct send). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/orders/arm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arm (stage) an order: evaluate the risk gate without transmitting. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/orders/send-as-is": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Opt-in fast path: send an order as-is. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/orders/conditional": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a conditional (triggered) order. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConditionalOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit a staged (armed) order. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Cancel a staged or working order. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/take": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take a staged order: re-validate everything fresh, then transmit. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile a stranded (mid-take) order against venue truth: adopt if live, release if flat. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modifies a <b>working</b> order in place (gh#259/gh#267/gh#278/gh#292, ADR-0007) — the venue-facing sibling of
         *     the cancel. Unlike a cancel (risk-reducing, gate-exempt), a modify can add risk (a likelier-to-fill entry, a
         *     wider stop, a larger size), so it runs the <b>full</b> send ladder and is re-gated before the venue is
         *     touched: the gate must approve the new terms, or nothing is transmitted (enforcement below the model). It can
         *     move the entry, re-stage the hidden working stop, and/or <b>resize</b> the order; the <b>safety stop</b> is
         *     held invariant on every path. A working-stop-only move with no size change re-stages locally (no venue call).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ModifyWorkingOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/conditionals/{id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile a stranded (mid-fire) conditional against venue truth: adopt if live, release if flat. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conditionals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a pending conditional (send-when-conditions-met) order — an operator withdrawal. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current kill-switch state. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Engage the kill switch (hold-to-confirm): stop new orders, cancel working orders, flatten or halt. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EngageKillSwitchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch/disengage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disengage the kill switch, re-enabling outbound orders. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reconcile and read the account's open positions against venue truth. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketdata/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OHLCV bars for a venue + instrument + resolution over a bounded time window (ascending). */
        get: {
            parameters: {
                query: {
                    venue: string;
                    instrument: string;
                    resolution: number | string;
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketdata/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A stored indicator series (e.g. atr, rsi) over a bounded time window — never recomputed (R-22). */
        get: {
            parameters: {
                query: {
                    venue: string;
                    instrument: string;
                    resolution: number | string;
                    indicator: string;
                    period: number | string;
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketdata/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active price levels for a venue + instrument across the requested timeframes. */
        get: {
            parameters: {
                query: {
                    venue: string;
                    instrument: string;
                    timeframes: (number | string)[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A request to accept an invitation and create the account. */
        AcceptInviteRequest: {
            /** @description The invite token from the invitation. */
            token: string;
            /** @description The chosen plaintext password. */
            password: string;
            /** @description The chosen display name. */
            displayName: string;
        };
        /**
         * @description Where an account sits in a firm's programme. Read from what the venue reports — for ProjectX that means the
         *     account <b>name</b>, which really does encode size, stage, and status.
         */
        AccountStage: number;
        /**
         * @description Which way price must cross the trigger for a conditional order to fire (ADR-0007, gh#176). A <b>refusable
         *     zero</b>: ConditionalCrossDirection.Unknown is the unset value and never fires — a direction must be declared, or the
         *     order would rest forever.
         */
        ConditionalCrossDirection: number;
        /**
         * @description How the gate treats a breached consistency target (gh#380).
         * @default 0
         */
        ConsistencyEnforcement: number;
        /**
         * @description The request to create a <b>synthetic conditional</b> entry order (gh#176, ADR-0007) — the "send when
         *     conditions met" mode. The proposal rides an ordinary SendOrderRequest; the conditional part is
         *     the trigger and its cancel-if / expiry.
         */
        CreateConditionalOrderRequest: {
            /** @description The entry proposal to hold and fire when the trigger crosses. */
            order: components["schemas"]["SendOrderRequest"];
            /**
             * Format: double
             * @description The price at which the order fires.
             */
            triggerPrice: number | string;
            /** @description Which way price must cross the trigger to fire (RisesTo / FallsTo). */
            triggerDirection: components["schemas"]["ConditionalCrossDirection"];
            /**
             * Format: double
             * @description The optional cancel band — the stale-side price past which the setup is abandoned.
             */
            cancelDrift?: null | number | string;
            /**
             * Format: date-time
             * @description The optional validity deadline; past it, a still-pending order cancels.
             */
            expiresAt?: null | string;
        };
        /** @description The request to register a firm login (ADR-0016: one per firm × platform). */
        CreateConnectionRequest: {
            /**
             * Format: uuid
             * @description The firm this login belongs to.
             */
            firmId: string;
            /** @description The platform key (e.g. `projectx`). Only wired adapters are accepted. */
            platform: string;
            /** @description The <b>non-secret</b> env-entry name the credentials live under. */
            credentialKey: string;
        };
        /** @description The request to register a firm the operator trades with. */
        CreateFirmRequest: {
            /** @description The firm's name (e.g. `Topstep`). */
            name: string;
            /** @description Prop firm (staged) or brokerage (live/paper only). */
            type: components["schemas"]["FirmType"];
        };
        /** @description The body of a create-trigger request (gh#385). Only the indicator-threshold kind is authored today. */
        CreateTriggerRequest: {
            /** @description The venue-neutral instrument symbol (e.g. `ES`). */
            symbol: string;
            /** @description The R-22 indicator name (`atr` / `rsi`), case-insensitive. */
            indicator: string;
            /**
             * Format: int32
             * @description The indicator period; must be positive.
             */
            period: number | string;
            /**
             * Format: int32
             * @description The bar size in minutes; must be positive.
             */
            resolutionMinutes: number | string;
            /** @description Below or Above; Unknown is refused. */
            comparison: components["schemas"]["IndicatorComparison"];
            /**
             * Format: double
             * @description The threshold to compare against.
             */
            threshold: number | string;
            /** @description Where a fire routes; Mechanical or AgentReview. */
            route: components["schemas"]["TriggerRoute"];
            /**
             * Format: double
             * @description The optional re-arm dead-band; null means none, and it must be positive when set.
             */
            hysteresis?: null | number | string;
            /** @description How loudly the alert arrives; defaults to NotificationSeverity.Notify. */
            severity?: components["schemas"]["NotificationSeverity"];
            /**
             * Format: uuid
             * @description The account a fired agent-review suggestion issues against — <b>required</b> for AgentReview (owned + mode
             *     declared), <b>refused</b> for Mechanical. Null otherwise.
             */
            accountId?: null | string;
            /**
             * Format: int32
             * @description The contract size a fired agent-review suggestion issues at — <b>required</b> and positive for AgentReview,
             *     <b>refused</b> for Mechanical. The operator's size, never the model's.
             */
            size?: null | number | string;
        };
        /** @description The request to declare a firm's full set of stage conventions (replaces any existing). */
        DeclareConventionsRequest: {
            /** @description The declarations. Each stage may appear at most once, and none may be Unknown. */
            conventions: components["schemas"]["StageConventionDto"][];
        };
        /**
         * @description The request to declare an account's risk rules (R-5, gh#10) — the complete declaration; a redeclaration
         *     replaces the whole profile.
         */
        DeclareRiskProfileRequest: {
            /**
             * Format: double
             * @description The hard daily loss limit; null when the account has none.
             */
            dailyLossLimit: null | number | string;
            /**
             * Format: double
             * @description The account's profit target (evaluation accounts); null otherwise.
             */
            accountProfitTarget: null | number | string;
            /**
             * Format: double
             * @description The account's declared starting balance — where the floor starts from. Positive.
             */
            startingBalance: number | string;
            /** @description Whether the loss floor is firm-imposed or self-imposed. */
            floorSource: components["schemas"]["FloorSource"];
            /** @description How the drawdown floor trails — end-of-day or intraday. */
            trailingMode: components["schemas"]["TrailingMode"];
            /**
             * Format: double
             * @description The trailing distance below the equity high-water mark. Positive.
             */
            trailingAmount: number | string;
            /**
             * Format: double
             * @description The ceiling the floor stops trailing at, if any.
             */
            locksAt: null | number | string;
            /**
             * Format: double
             * @description Risk per trade as a fraction of headroom to the floor — in (0, 1].
             */
            perTradeRiskFraction: number | string;
            /**
             * Format: double
             * @description The target reward-to-risk ratio. Positive.
             */
            targetRewardRatio: number | string;
            /**
             * Format: double
             * @description The per-trade hard loss cap. Positive.
             */
            maxDrawdownPerTrade: number | string;
            /**
             * Format: double
             * @description The personal daily governor. Positive.
             */
            dailyDrawdownGovernor: number | string;
            /**
             * Format: double
             * @description The personal daily profit target; null means none.
             */
            dailyProfitTarget: null | number | string;
            /** @description Whether reaching the daily target stops trading for the day. */
            stopForDayAtProfitTarget: boolean;
            /** @description Whether sizing uses the working stop or the safety stop. */
            sizingBasis: components["schemas"]["SizingBasis"];
            /**
             * Format: int32
             * @description The manual per-order contract cap; 0 means uncapped.
             */
            maxContractsPerOrder: number | string;
            /**
             * Format: double
             * @description The consistency target — best day ÷ total net profit, in (0, 1]; null means none.
             */
            maxBestDayFraction: null | number | string;
            /** @description Whether breaching that target refuses the order or only warns (gh#380); only consulted when a target is set. */
            consistencyEnforcement?: components["schemas"]["ConsistencyEnforcement"];
            /** @description Which entry action is primary on the Approve split button (R-11, gh#218). Defaults to `ApproveAndArm` (review-first); `SendAsIs` is practice-only and requires ConfirmSendAsIsDefault. */
            defaultEntryAction?: components["schemas"]["DefaultEntryAction"];
            /**
             * @description The explicit confirmation required to default to `SendAsIs` — a request that sets `SendAsIs` without it is refused 422 (the kill switch's hold-to-confirm shape).
             * @default false
             */
            confirmSendAsIsDefault: boolean;
        };
        /**
         * @description Which entry action is the operator's <b>default</b> — the primary half of the Approve split button (R-11,
         *     ADR-0007, gh#218).
         * @default 0
         */
        DefaultEntryAction: number;
        /** @description A request to engage the kill switch (gh#189). */
        EngageKillSwitchRequest: {
            /** @description Flatten all open positions (default) or halt only (leave them on native safety stops). */
            mode: components["schemas"]["KillSwitchMode"];
            /** @description The hold-to-confirm gesture — must be `true` to engage. */
            confirmed: boolean;
            /** @description The operator's reason, optional, journaled with the action. */
            reason: null | string;
        };
        /**
         * @description What kind of account provider a Firm is. A <b>prop firm</b> runs staged programmes
         *     (evaluation → funded); a <b>brokerage</b> does not — its accounts are simply live or paper. The distinction
         *     matters because stage conventions (gh#60) apply to prop firms only (gh#76).
         */
        FirmType: number;
        /**
         * @description Where the loss floor comes from. The risk-budget dynamic is identical either way — only the origin and the
         *     consequence of a breach differ (R-5).
         */
        FloorSource: number;
        /** @description How an indicator value is compared to a threshold in a trigger condition (R-4 / R-7, ADR-0008). */
        IndicatorComparison: number;
        /** @description A request to issue an onboarding invitation. */
        IssueInvitationRequest: {
            /** @description The email to invite. */
            email: string;
        };
        /** @description What the kill switch does to <b>open positions</b> when engaged (ADR-0007, R-11, gh#189). */
        KillSwitchMode: number;
        /** @description A login request. */
        LoginRequest: {
            /** @description The user's email. */
            email: string;
            /** @description The user's plaintext password. */
            password: string;
        };
        /**
         * @description The request to modify a <b>working</b> order in place — a PATCH that moves the resting <b>entry</b> at the venue
         *     (gh#259), re-stages the hidden <b>working stop</b> (gh#267), moves <b>both together</b> (gh#278), and/or
         *     <b>resizes</b> the order (gh#292). At least one of decimal? ModifyWorkingOrderRequest.EntryPrice / decimal? ModifyWorkingOrderRequest.WorkingStopPrice /
         *     int? ModifyWorkingOrderRequest.Size must be present (a int? ModifyWorkingOrderRequest.Size equal to the order's current size is a no-op). The
         *     <b>safety stop</b> stays invariant on every path, so the R-5 catastrophic floor is untouched; the full chain
         *     `safety → working → entry` is re-validated before the venue is touched.
         */
        ModifyWorkingOrderRequest: {
            /**
             * Format: double
             * @description The new entry price, or `null` to leave it. When present, the entry reprices at the venue and
             *     re-gates (gh#259); decimal? ModifyWorkingOrderRequest.ReferencePrice is then required.
             */
            entryPrice: null | number | string;
            /**
             * Format: double
             * @description The new <b>hidden</b> working-stop price, or `null` to leave it (gh#267). A hidden stop is a
             *     promotion target, not a venue order, so re-staging it <b>alone</b> is a <b>local</b> write — no venue call. It
             *     re-gates <b>only</b> when it <i>widens</i> under `SizingBasis.ActualStop` (the one enforced layer measured
             *     at the working stop). Moving it onto the safety stop (removing it) is out of scope.
             */
            workingStopPrice?: null | number | string;
            /**
             * Format: double
             * @description The <b>caller's</b> current market reference the fat-finger band re-measures a new <b>entry</b> against (R-16)
             *     — <b>required when decimal? ModifyWorkingOrderRequest.EntryPrice is present</b>. Caller-supplied, as on every order path (the server
             *     fetches no venue quote), so it is the client's freshness, not the venue's. A move that does not touch the entry
             *     (a working-stop re-stage or a pure resize) does not need it.
             */
            referencePrice?: null | number | string;
            /**
             * Format: int32
             * @description The new contract quantity, or `null` to leave it (gh#292). A resize re-gates at the new size and
             *     modifies the order in place at the venue, transmitting the <b>gate-approved</b> quantity (a downsize the gate
             *     binds is honoured, never silently exceeded). The always-native safety bracket carries no size of its own — the
             *     gateway attaches it <i>on fill</i>, sized to the realized fill — so a resize leaves the eventual fill protected
             *     by construction (verified on practice before live, gh#293). `&lt;= 0` is refused; the order must be
             *     `Working` (a partially-filled order is refused, closing the only stale-bracket-size window).
             */
            size?: null | number | string;
        };
        /** @description A star/mute request on a news item (gh#27). The dedup key rides in the body — it is a URL, not path-safe. */
        NewsFeedbackRequest: {
            /** @description The rated item's dedup key (its NewsRecord primary key). */
            dedupKey: string;
            /** @description Star or mute (never SoftSignalKind.Unknown). */
            kind: components["schemas"]["SoftSignalKind"];
        };
        /**
         * @description How loudly a notification should arrive (gh#243, ADR-0019's P1/P2/P3 taxonomy).
         * @default 1
         */
        NotificationSeverity: number;
        /** @description Which way an order goes. Venue wire values differ (ProjectX sends 0 bid / 1 ask); adapters map. */
        OrderSide: number;
        /**
         * @description The venue-neutral order types. Deliberately the common set — venue-specific extras (ProjectX
         *     `JoinBid`/`JoinAsk`) stay out of the core, and types not every venue offers are gated by
         *     VenueCapability rather than assumed (R-17).
         * @default 0
         */
        OrderType: number;
        /**
         * @description The body of a patch-trigger request (gh#385). Every field is optional — null means "leave unchanged". The
         *     debounce state (`ArmState`, `ArmCycle`, `LastFiredAt`, `LastEvaluatedValue`) is deliberately
         *     absent: it is the scan's and the journal's, never the caller's, and any edit re-seeds the arm state silently.
         */
        PatchTriggerRequest: {
            /** @description Enable or disable the trigger. */
            enabled?: null | boolean;
            /**
             * Format: double
             * @description A new threshold.
             */
            threshold?: null | number | string;
            /**
             * Format: double
             * @description A new re-arm dead-band; must be positive when set (clearing it is not offered here).
             */
            hysteresis?: null | number | string;
            comparison?: null | components["schemas"]["IndicatorComparison"];
            severity?: null | components["schemas"]["NotificationSeverity"];
        };
        /** @description Rotate which credential key a connection names (gh#210, ADR-0015). */
        RotateCredentialsRequest: {
            /** @description The new credential key this connection should name. */
            credentialKey: string;
        };
        /**
         * @description The request to send one order through the gate (gh#11). The instrument's tick size and point value ride the
         *     request because no Instrument entity exists yet (recorded on the dictionary §1 row) — the caller supplies
         *     the spec the risk math needs.
         */
        SendOrderRequest: {
            /** @description The venue-neutral instrument symbol (e.g. `MES`). */
            symbol: string;
            /**
             * Format: double
             * @description The instrument's tick size.
             */
            tickSize: number | string;
            /**
             * Format: double
             * @description The instrument's point value (currency per point per contract).
             */
            pointValue: number | string;
            /** @description Buy or sell. */
            side: components["schemas"]["OrderSide"];
            /**
             * Format: int32
             * @description The contracts asked for — the gate decides what is actually authorized.
             */
            quantity: number | string;
            /**
             * Format: double
             * @description The intended entry price.
             */
            entry: number | string;
            /**
             * Format: double
             * @description The working stop price.
             */
            stop: number | string;
            /**
             * Format: double
             * @description The safety-stop price — the deterministic worst case (R-5).
             */
            safetyStop: number | string;
            /**
             * Format: double
             * @description The current reference price the fat-finger band measures from.
             */
            referencePrice: number | string;
            /** @description How the order rests. Trailing stops are refused (no trail distance on the ticket). */
            type?: components["schemas"]["OrderType"];
            /**
             * Format: double
             * @description The optional take-profit price (ADR-0007, gh#173) — the profit side of a native OCO bracket. It must sit on
             *     the <b>winning</b> side of Entry (above for a long, below for a short); a wrong-side
             *     target is refused before the gate. `null` means no profit leg (the two-leg bracket).
             */
            target?: null | number | string;
        };
        /** @description The request to declare an account's stage, overriding the conservative name-resolver (gh#76). */
        SetStageOverrideRequest: {
            /** @description The declared stage. `Unknown` is refused — clearing the override says that. */
            stage: components["schemas"]["AccountStage"];
        };
        /** @description Which stop the per-trade risk budget is divided by when sizing (configurable, R-5 / ADR-0007). */
        SizingBasis: number;
        /**
         * @description The kind of per-user feedback on a soft-signal / news item (gh#27, ADR-0014). A <b>refusable zero</b>:
         *     SoftSignalKind.Unknown is never a real kind — feedback must declare its intent — refused at construction and by a
         *     DB check. One entity (`SoftSignalFeedback`) unifies all kinds; <b>star</b> and <b>mute</b> ship now, and the
         *     👍/👎 <b>sentiment</b> (direction) axis is deferred (R-2) and will extend this enum without reshaping the store.
         */
        SoftSignalKind: number;
        /** @description One stage declaration — what a stage means at a firm (gh#60). */
        StageConventionDto: {
            /** @description The stage being classified. Never AccountStage.Unknown. */
            stage: components["schemas"]["AccountStage"];
            /** @description `true` if capital is at risk at this stage (maps to Live). */
            capitalAtRisk: boolean;
        };
        /**
         * @description Why the operator passed a Suggestion — the canonical <b>eight</b> reasons settled by gh#539, taken
         *     from the operator-validated pass sheet in the wireframes. A multi-select, so it is a `[Flags]` value stored
         *     in one integer and sliced by R-9 with a bitwise test.
         * @default 0
         */
        SuggestionPassReason: number;
        /**
         * @description The body of a pass (gh#547, R-4). <b>Both fields are optional</b>: a pass is a <b>neutral decline</b>, not a
         *     rejection, so the operator need give no reason at all.
         */
        SuggestionPassRequest: {
            /**
             * @description The pass reasons, a `[Flags]` multi-select. SuggestionPassReason.None (the default) is a valid,
             *     neutral pass.
             */
            reasons?: components["schemas"]["SuggestionPassReason"];
            /** @description An optional free-text note, capped at int SuggestionDisposition.NoteMaxLength. */
            note?: null | string;
        };
        SuggestionState: number;
        /**
         * @description The body of a take (gh#548, R-11b / R-12). Its <b>only</b> field is the current market reference — the two
         *     numbers a server-originated proposal cannot invent (the tick size, point value and safety-stop distance) come
         *     from the instrument-spec source, never the client (that is ruled out in writing on SendOrderRequest).
         */
        SuggestionTakeRequest: {
            /**
             * Format: double
             * @description The caller's current market price, as on every order path (the server fetches no venue quote). It does double
             *     duty: the take-time <b>drift re-check</b> re-measures it against the suggestion's entry tolerance <b>now</b>
             *     (R-12, not the eventually-consistent SuggestionState.Stale flag), and it is the fat-finger band's
             *     reference once the ticket reaches the gate (R-16). Must be positive.
             */
            referencePrice: number | string;
        };
        /** @description A ticker↔instrument map create request (gh#359). */
        TickerMapRequest: {
            /** @description The provider ticker (e.g. `SPY`). */
            ticker: string;
            /** @description The traded instrument it maps to (e.g. `ES`). */
            instrument: string;
        };
        /** @description A topic create / edit request (gh#359). PATCH replaces the topic whole. */
        TopicRequest: {
            /** @description The topic name (e.g. `fomc`). */
            name: string;
            /** @description The keywords that mark the topic matched. */
            keywords: string[];
            /** @description Instrument-scoped or global (never TopicScope.Unknown). */
            scope: components["schemas"]["TopicScope"];
            /** @description The instrument for an instrument-scoped topic; ignored for a global one. */
            instrument: null | string;
        };
        /**
         * @description A topic's reach (gh#359). A <b>refusable zero</b>: TopicScope.Unknown never matches — a topic must declare
         *     whether it is instrument-scoped or global, so an unset scope can't silently attach news to an instrument.
         *     Refused at construction and by a DB check.
         */
        TopicScope: number;
        /**
         * @description How an account's trailing drawdown floor moves. A property of the <b>account</b>, not the firm — Apex sells
         *     both kinds, so it is keyed off the account.
         */
        TrailingMode: number;
        /** @description Where a trigger fire routes (ADR-0008) — the two outcomes a trigger definition chooses between. */
        TriggerRoute: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
